import { Inter } from 'next/font/google';
import './globals.css';
import { UserProvider } from './context/UserContext'; 
import Navbar from './components/Navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <header className="header">          
          </header>
          <main>{children}</main>
          <footer className="footer">
            <p>&copy;  Maiu y Juli</p>
          </footer>
        </UserProvider>
      </body>
    </html>
  );
}