import { Inter } from 'next/font/google';
import './globals.css'; 
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <div className="logo">M&J Site</div>
          <nav>
            <Link href="./home">Home</Link>
            <Link href="./contacto">Contacto</Link>
            <div className="userInfo">
              {/* Estos valores deben ser dinámicos según el estado de autenticación */}
              <Link href="/contacto">User</Link>
              <Link href="./logIn">Log in</Link>
              <Link href="#" className="logoutButton">Logout</Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="footer">
          <p>&copy;  Maiu y Juli</p>
        </footer>
      </body>
    </html>
  );
}